### PR TITLE
Changed some stuff around.

### PR DESCRIPTION
**Pull request by BlockWorker**
- Worker and Task search _should_ now try to fill tasks to the same level, but they don't really want to .-.
- New onWorkTick() method in ITask, by default called every second by the existing onTick() (Our plan
  of 1 work every second)
- Changed work amount on TestTask to 20, as work now takes much longer

### CODE REVIEW

**Comment by BlockWorker** [comment]
I should learn not to make commit fails.

**Comment by BlockWorker** [comment]
Dammit Idea, did you really have to make a new commit for that merge?!?

**Comment by Itszuvalex** [comment]
Make sure to fix the Worker and Task ordering function to address the issues we discussed on irc.

**Comment by BlockWorker** [comment]
I couldn't talk to you today, but here's the current version of the new model:
http://puu.sh/jKPUZ/006b2e91a1.png

**Pull request merged**
